# Generated by Django 4.1.7 on 2023-02-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='type',
        ),
    ]
