# Generated by Django 4.1.7 on 2023-02-24 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_author_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('from_author_request', models.BooleanField(default=False)),
                ('to_author_request', models.BooleanField(default=False)),
                ('from_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from_author', to='core.author')),
                ('to_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to_author', to='core.author')),
            ],
        ),
        migrations.AddConstraint(
            model_name='relations',
            constraint=models.UniqueConstraint(fields=('from_author', 'to_author'), name='There can only be this relation between two authors'),
        ),
    ]
