# Generated by Django 4.1.7 on 2023-02-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_relations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relations',
            new_name='Relation',
        ),
    ]
