# Generated by Django 4.1.7 on 2023-02-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_relations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://127.0.0.1:5454'),
        ),
    ]
