# Generated by Django 4.1.7 on 2023-02-24 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_relations_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='from_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.author'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='core.author'),
        ),
    ]
