# Generated by Django 4.1.7 on 2023-02-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_caption_alter_post_image'),
        ('core', '0006_alter_relation_from_author_alter_relation_to_author'),
    ]

    operations = [
    ]
