# Generated by Django 4.1.7 on 2023-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_comments_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
