# Generated by Django 4.1.7 on 2023-03-24 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_comments_alter_author_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAdmin',
            fields=[
                ('m_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('host', models.URLField()),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
