# Generated by Django 4.1.7 on 2023-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_follower_approved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='Unique user properties',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('id',), name='Unique user properties'),
        ),
    ]
