# Generated by Django 4.1.7 on 2023-03-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_host'),
        ('core', '0004_remove_author_unique user properties_and_more'),
    ]

    operations = [
    ]
