# Generated by Django 4.1.7 on 2023-03-27 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_clientserver_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientServer',
            new_name='Node',
        ),
    ]
