# Generated by Django 4.1.7 on 2023-03-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20230326_2255'),
        ('core', '0005_merge_20230327_0512'),
        ('core', '0007_rename_clientserver_node'),
    ]

    operations = [
    ]
