# Generated by Django 4.1.7 on 2023-03-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_author_avatar_alter_author_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='password',
        ),
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
        migrations.RemoveField(
            model_name='node',
            name='username',
        ),
    ]
