# Generated by Django 4.1.7 on 2023-03-29 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_node_password_remove_node_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
