# Generated by Django 4.1.7 on 2023-03-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(),
        ),
    ]
