# Generated by Django 4.1.7 on 2023-03-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://localhost:8000'),
        ),
    ]
