# Generated by Django 4.1.7 on 2023-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='host',
        ),
        migrations.AddField(
            model_name='node',
            name='api_endpoint',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(default='text/plain', max_length=512),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(default='comment', max_length=512),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='summary',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='type',
            field=models.CharField(default='like', max_length=512),
        ),
        migrations.AlterField(
            model_name='follower',
            name='summary',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='type',
            field=models.CharField(default='post', max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=512),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='summary',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='type',
            field=models.CharField(default='like', max_length=512),
        ),
    ]
