# Generated by Django 4.1.7 on 2023-03-21 05:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_author_url_alter_comment_url_alter_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('m_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_private',
        ),
        migrations.AddField(
            model_name='inbox',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='inbox',
            name='type',
            field=models.CharField(default='post', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=300),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.AddField(
            model_name='follower',
            name='from_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.author'),
        ),
        migrations.AddField(
            model_name='follower',
            name='to_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='core.author'),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('from_author', 'to_author'), name='There can only be this relation between two authors'),
        ),
    ]
