# Generated by Django 4.1.7 on 2023-03-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_follower_approved'),
        ('core', '0003_serveradmin'),
    ]

    operations = [
    ]
