# Generated by Django 4.1.7 on 2023-03-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_host'),
        ('core', '0003_alter_follower_approved'),
    ]

    operations = [
    ]
