# Generated by Django 4.1.7 on 2023-03-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_private',
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(max_length=300),
        ),
    ]
