# Generated by Django 4.1.7 on 2023-03-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_inbox_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
