# Generated by Django 4.1.7 on 2023-03-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_is_private_post_unlisted_post_visibility_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relation',
            new_name='Follower',
        ),
    ]
