# Generated by Django 4.1.7 on 2023-03-26 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_merge_0003_alter_follower_approved_0003_serveradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServer',
            fields=[
                ('m_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('host', models.URLField()),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_server', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServerAdmin',
        ),
    ]
