# Generated by Django 4.1.7 on 2023-03-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_github_alter_inbox_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
