# Generated by Django 4.1.7 on 2023-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inbox_content_type_alter_inbox_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='summary',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
