# Generated by Django 4.1.7 on 2023-03-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_follower_summary_alter_inbox_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
