# Generated by Django 4.1.7 on 2023-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20230327_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
