# Generated by Django 4.1.7 on 2023-03-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_inbox_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='content_type',
            new_name='c_type',
        ),
    ]
