# Generated by Django 4.1.7 on 2023-03-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_content_type_inbox_c_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='c_type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='follower',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
